# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-11 22:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('My application', '0003_auto_20171006_2005'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_person', to='My application.Event')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_event', to='My application.Person')),
            ],
        ),
    ]
